### ISSUE TITLE
compiling a Rnw file from TexMaker or TexStudio

### ISSUE THREAD

**Issue by jvega68** [Eflores89/banxicoR#1]
Hi Luis:
Not sure this is an issue, but here we go. I am compiling a Rnw file from `TexMaker` and/or TexStudio in Kubuntu 15.10 with the following command:

`Rscript -e "library(knitr); knit2pdf('%.Rnw')" | pdflatex -synctex=1 -interaction=nonstopmode %.tex`

 My minimal file is as follows:

```
\documentclass[10pt,letter]{beamer}
\usepackage{graphicx}
\usepackage{beamerthemesplit}
\usepackage{amsmath}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[spanish]{babel}

\begin{document}
<<setup, include=FALSE>>=
library(knitr)
opts_chunk$set(fig.path = 'Efigs', 'fig.show' = 'as.is', fig.height = 5, fig.align = 'center', 
               cahe=F, size = 'scriptsize',fig.align="center")
par(width=100)
library(banxicoR) 
@
\begin{frame}[fragile]{Ejemplos: tipos de cambio}
<<echo=FALSE>>=
datos <- banxico_series(series ="SF60653")
plot(datos$SF60653, main = "Tipo de cambio diario", xlab = "t", ylab = "MXN/USD", type = "l")
@
\end{frame}
\end{document}
```

The following error message appears in the compiled file (that I cannot attach):

 ## Error in as.vector(x, "list"): cannot coerce type ’environment’ to vector of
   type ’list’
   ## Error in plot(datos$SF60653, main = "Tipo de cambio diario", xlab = "t", :
   objeto ’datos’ no encontrado

If I compile the file from Rstudio, I don't have any problem.

**Comment by Eflores89** [comment]
The following works fine (withouth knitting) :

```
library(banxicoR)
datos <- banxico_series(series ="SF60653")
plot(datos$SF60653, main = "Tipo de cambio diario", xlab = "t", ylab = "MXN/USD", type = "l")
```

And because you say you can compile from Rstudio, I would guess the issue is not `banxicoR` but knitr or your personal setup (the environment in which you are calling R from). Maybe you could try opening the issue here: https://github.com/yihui/knitr/issues

And include the output from `devtools::sesion_info()`
